### ISSUE TITLE
should we consider moving this repo to https://github.com/euroargodev org?

### ISSUE THREAD

**Issue by gaelforget** [euroargodev/ArgoData.jl#34]
@gmaze , what do you think?

I put this originally in JuliaOcean but am now thinking it would fit and might be more helpful under your org

**Comment by gmaze** [comment]
It's totally up to you !
I guess it depends on the visibility and the community you expect to be in most contact with
You could transfer the repo to euroargodev, since it's the primary user base, and for it back here, so that it remains visible to Julia Ocean enthusiast

**Comment by gmaze** [comment]
I'll send you an invitation from euroargodev as "outside collaborator" and give you all the necessary access to create repo and enjoy the euroargodev Argo collaborative framework ;-)

**Comment by gaelforget** [comment]
Great! 

Do you mind if we proceed as follows?

- creating a team on the org side for the repo owners
- adding the repo to the team / making team admin of repo
- inviting pkg dev to org member
- adding pkg dev to the team

That's what we do in [JuliaClimate](https://github.com/orgs/JuliaClimate/teams) and [MITgcm](https://github.com/orgs/MITgcm/teams) for example. or recently with [Dataverse.jl](https://github.com/gdcc/Dataverse.jl/issues/4)

On the org side, only someone with sufficient / owner privileges can create teams and so on. Details may depend on how you have the org set up.

One advantage, as compared to creating a fresh repo, is that everything in the original repo carries over -- i.e., issues, discussions, settings, ci, docs, zenodo links, webhooks, tags, etc. If instead of using the GitHub transfer mechanism I just push the git history into a fresh repo then the rest is lost.

@gmaze  , could we do the transfer this way via the GitHub ownership transfer?

**Comment by gmaze** [comment]
I think you can feel reinsured that a transfer will preserve basically every thing ([see here for details](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository)) and even ensure url forwarding from initial routes to the new ones !

i just sent you an invitation to become a member of euroargodev.
I guess from there, you will be able to create repositories (and transfert this one) and to create teams. 
Note that any pkg developers does not need to be a euroargodev member to contribute

**Comment by gaelforget** [comment]
Sounds good. I just joined. Will now transfer ownership to @euroargodev

Afterwards I will need to do a couple checks wrt GitHub actions & bots (docs -> pages, ci, releases, tagbot). I think I recall that one can get broken by transfer. Will see.

**Comment by gaelforget** [comment]
So, I believe I do need owner privileges on this repo (not the whole org). 

For example I cannot edit the URL :

![Screenshot 2022-12-02 at 3 38 20 PM](https://user-images.githubusercontent.com/20276764/205317608-aac74b4e-f362-4ce1-82f5-4615a5e7c56e.png)

There should be a `wheel` in the top right like here :

![Screenshot 2022-12-02 at 3 40 25 PM](https://user-images.githubusercontent.com/20276764/205317835-a36d41a9-2cba-4018-a9f3-c182a4c48a9b.png)

A simple way to do this in a compartmented way is by creating a team etc as outlined in https://github.com/euroargodev/ArgoData.jl/issues/34#issuecomment-1335042556

**Comment by gaelforget** [comment]
@gmaze , I was able to create [new team](https://github.com/orgs/euroargodev/teams/argodata-jl) but dont think I can go further. Unless I am mistaken you need to give me owner privilege on the repo so I can add it to the team. Please correct me if I am wrong.

**Comment by gmaze** [comment]
you're now admin of the repo ...

**Comment by gaelforget** [comment]
thanks @gmaze
